In [1]:
import pandas as pd
import numpy as np
from BLP import UtilityEstimation


In [2]:
theta_1_true = np.array([-0.5, 1.0, 0.8])  
pi_true = np.array([[0.1, -0.05],
                    [0.2, 0.1],
                    [-0.1, 0.05]])      
sigma_true = np.array([0.2, 0.5, 0.3]) 

In [3]:
df_char=pd.read_csv('characteristics.csv')
df_char.drop(['Unnamed: 0'],axis=1,inplace=True)

In [4]:
df_char.to_numpy().shape

(50, 3)

In [5]:
df_demo=pd.read_csv('demographics.csv')
df_demo.drop(['Unnamed: 0'],axis=1,inplace=True)

In [6]:
df_demo.to_numpy().shape

(1000, 2)

In [7]:
df_IV=pd.read_csv('IV.csv')
df_IV.drop(['Unnamed: 0'],axis=1,inplace=True)

In [8]:
df_IV.to_numpy().shape

(50, 4)

In [9]:
df_share=pd.read_csv('share.csv')


In [10]:
df_share['Share'].to_numpy().shape

(50,)

In [11]:
obj=UtilityEstimation(
    X=df_char.to_numpy(),s_jt=df_share['Share'].to_numpy(), D=df_demo.to_numpy(), ns=1000, seed=42
)

In [12]:
delta,status=obj.blp_contraction_mapping(theta_1=theta_1_true, pi=pi_true, sigma=sigma_true)

In [13]:
status

True

In [15]:
pd.DataFrame(delta).head()

0
0 -3.086515
1 -2.938528
2 -3.150705
3 -2.802572
4 -3.026855

In [16]:
error =obj.compute_xi(delta=delta,theta_1=theta_1_true,X=df_char.to_numpy())


In [17]:
error

array([-13.67437305,  -9.86177843,  -8.51474361,   1.73457851,
        -2.41163043,  -5.25777762, -10.99917908,  -0.54490697,
        -3.18813128,  -3.1957844 ,  -8.92894014,   0.92340126,
        -6.15517942,  -6.35416909,  -2.76581212, -11.88688359,
        -0.78741056,  -0.9716451 ,  -8.44637425,  -9.85301677,
        -1.21185793, -10.28287502,  -8.27218906,  -4.48826865,
         3.53021093,   1.69054198,  -4.1906931 ,  -5.55160419,
        -4.09720524,  -0.65558387,   1.89310991, -12.6510042 ,
       -10.79736908,  -0.23844753,  -4.08395527,  -6.87401285,
         0.48827656,  -2.69599368,  -7.71735191,   1.81095972,
        -2.64274864,   2.36507888,  -9.134218  ,  -0.99724938,
        -6.4925202 ,  -3.54900971,  -2.11234809,   3.95517577,
        -2.7635137 ,   2.10785877])

In [18]:
m=obj.compute_moments(xi=error,Z=df_IV.to_numpy())

In [19]:
m

array([ 0.62724203,  0.67705461, -0.65459943, -0.13751097])

In [26]:
pi_true.flatten()


array([ 0.1 , -0.05,  0.2 ,  0.1 , -0.1 ,  0.05])

In [27]:
objective=obj.gmm_objective(
    theta_params=np.hstack([theta_1_true,pi_true.flatten(),sigma_true]),
    Z=df_IV.to_numpy()
)

In [28]:
objective

1.2992451875492357

In [29]:
dict_r=obj.estimate_parameters(
    initial_theta=np.hstack([theta_1_true,pi_true.flatten(),sigma_true]),
    Z=df_IV.to_numpy()
)

In [30]:
dict_r

{'theta': array([-0.5 ,  1.  ,  0.84,  0.1 , -0.05,  0.2 ,  0.1 , -0.1 ,  0.05,
         0.2 ,  0.5 ,  0.3 ]),
 'delta': array([-3.07507623, -2.97496647, -3.19796223, -2.55947337, -2.83549485,
        -2.657219  , -2.61461382, -2.28590076, -2.36906259, -2.4389896 ,
        -2.02914499, -2.27670262, -1.96797933, -1.84977763, -1.84274526,
        -2.07282542, -1.4557117 , -1.50460989, -1.72297135, -1.75478249,
        -1.36265982, -1.63402981, -1.17926361, -0.93785046, -0.99465587,
        -1.22577477, -0.85805742, -0.61658482, -0.87280464, -0.30944102,
        -0.71918819, -0.66975174, -0.506626  , -0.07894387, -0.48011252,
        -0.23080555,  0.04159465, -0.08167174, -0.30590754,  0.2825088 ,
         0.12558597,  0.237273  ,  0.31479939,  0.53518988,  0.40996177,
         0.84158354,  0.63047103,  1.00490333,  0.8736551 ,  1.17544297]),
 'xi': array([-13.97298733, -10.25614833,  -8.93075102,   1.8992842 ,
         -2.35040272,  -5.15336487, -10.96308976,  -0.65757186,
         -3.50

In [32]:
dict_r['theta'].shape

(12,)

In [33]:
theta_1_true

array([-0.5,  1. ,  0.8])

In [34]:
pi_true

array([[ 0.1 , -0.05],
       [ 0.2 ,  0.1 ],
       [-0.1 ,  0.05]])

In [35]:
sigma_true

array([0.2, 0.5, 0.3])

In [36]:
dict_r['theta']

array([-0.5 ,  1.  ,  0.84,  0.1 , -0.05,  0.2 ,  0.1 , -0.1 ,  0.05,
        0.2 ,  0.5 ,  0.3 ])